name: Photography by Kaipo Kiaha
favicon: null
layout_spectrum: 0.03800682839937508
typography_spectrum: 0.18406373751349747
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#17BEBB'
    - '#2E282A'
    - '#CD5334'
    - '#EDB88B'
    - '#FAD8D6'
  brandStrength: 0.4592496978584677
  lightness: 0.2158931775484234
  saturation: 0.467051487416029
  rhythmicContrast: 0.8089065041858703
purpose: []
